[2023-12-21T12:58:57.046-0300] {processor.py:161} INFO - Started process (PID=7107) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T12:58:57.048-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T12:58:57.050-0300] {logging_mixin.py:188} INFO - [2023-12-21T12:58:57.049-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T12:58:57.079-0300] {logging_mixin.py:188} INFO - [2023-12-21T12:58:57.079-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T12:58:57.082-0300] {logging_mixin.py:188} INFO - [2023-12-21T12:58:57.080-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T12:58:57.082-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T12:58:57.174-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.135 seconds
[2023-12-21T13:00:06.441-0300] {processor.py:161} INFO - Started process (PID=7178) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:00:06.443-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:00:06.445-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:00:06.444-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:00:06.455-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:00:06.455-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:00:06.458-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:00:06.456-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:00:06.459-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:00:06.563-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.128 seconds
[2023-12-21T13:01:19.293-0300] {processor.py:161} INFO - Started process (PID=7274) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:01:19.296-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:01:19.298-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:01:19.297-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:01:19.308-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:01:19.307-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:01:19.311-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:01:19.308-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:01:19.312-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:01:19.418-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.132 seconds
[2023-12-21T13:02:25.944-0300] {processor.py:161} INFO - Started process (PID=7355) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:02:25.956-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:02:25.958-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:02:25.957-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:02:25.968-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:02:25.967-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:02:25.971-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:02:25.968-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:02:25.972-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:02:26.066-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.129 seconds
[2023-12-21T13:03:26.813-0300] {processor.py:161} INFO - Started process (PID=7420) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:03:26.814-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:03:26.816-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:03:26.815-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:03:26.823-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:03:26.823-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:03:26.826-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:03:26.824-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:03:26.826-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:03:26.939-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.131 seconds
[2023-12-21T13:04:26.822-0300] {processor.py:161} INFO - Started process (PID=7477) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:04:26.824-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:04:26.826-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:04:26.825-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:04:26.833-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:04:26.833-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:04:26.836-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:04:26.834-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:04:26.837-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:04:26.961-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.144 seconds
[2023-12-21T13:05:28.144-0300] {processor.py:161} INFO - Started process (PID=7537) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:05:28.146-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:05:28.148-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:05:28.147-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:05:28.159-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:05:28.158-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:05:28.162-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:05:28.159-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:05:28.163-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:05:28.383-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.248 seconds
[2023-12-21T13:06:48.887-0300] {processor.py:161} INFO - Started process (PID=7689) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:06:48.908-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:06:48.910-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:06:48.910-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:06:48.921-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:06:48.920-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:06:48.924-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:06:48.921-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:06:48.925-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:06:49.047-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.166 seconds
[2023-12-21T13:08:04.101-0300] {processor.py:161} INFO - Started process (PID=8021) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:08:04.103-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:08:04.105-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:08:04.104-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:08:04.115-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:08:04.114-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:08:04.118-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:08:04.115-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:08:04.119-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:08:04.218-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.125 seconds
[2023-12-21T13:09:06.324-0300] {processor.py:161} INFO - Started process (PID=9209) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:09:06.326-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:09:06.327-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:09:06.326-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:09:06.333-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:09:06.333-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:09:06.335-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:09:06.333-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:09:06.335-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:09:06.457-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.138 seconds
[2023-12-21T13:10:15.272-0300] {processor.py:161} INFO - Started process (PID=9395) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:10:15.279-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:10:15.281-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:10:15.280-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:10:15.291-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:10:15.291-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:10:15.295-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:10:15.292-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:10:15.296-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:10:15.460-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.195 seconds
[2023-12-21T13:11:22.859-0300] {processor.py:161} INFO - Started process (PID=9778) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:11:22.884-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:11:22.886-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:11:22.886-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:11:22.898-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:11:22.897-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:11:22.901-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:11:22.898-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:11:22.902-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:11:23.002-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.150 seconds
[2023-12-21T13:12:25.891-0300] {processor.py:161} INFO - Started process (PID=10078) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:12:25.893-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:12:25.895-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:12:25.894-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:12:25.905-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:12:25.905-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:12:25.909-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:12:25.906-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:12:25.910-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:12:26.083-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.200 seconds
[2023-12-21T13:13:28.140-0300] {processor.py:161} INFO - Started process (PID=10285) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:13:28.142-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:13:28.144-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:13:28.143-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:13:28.154-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:13:28.154-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:13:28.158-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:13:28.155-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:13:28.158-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:13:28.255-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.122 seconds
[2023-12-21T13:14:31.230-0300] {processor.py:161} INFO - Started process (PID=10343) to work on /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:14:31.233-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/reports/create_sql_script.py for tasks to queue
[2023-12-21T13:14:31.235-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:14:31.234-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:14:31.245-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:14:31.245-0300] {create_sql_script.py:18} INFO - <class 'Exception'>
[2023-12-21T13:14:31.248-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:14:31.246-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/reports/create_sql_script.py", line 1411, in <module>
    schedule_interval=hour_changer("00 10 * * *  "),
NameError: name 'hour_changer' is not defined
[2023-12-21T13:14:31.249-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/reports/create_sql_script.py
[2023-12-21T13:14:31.361-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/reports/create_sql_script.py took 0.137 seconds
