[2023-12-21T12:58:58.440-0300] {processor.py:161} INFO - Started process (PID=7108) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T12:58:58.442-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T12:58:58.444-0300] {logging_mixin.py:188} INFO - [2023-12-21T12:58:58.443-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T12:58:58.453-0300] {logging_mixin.py:188} INFO - [2023-12-21T12:58:58.451-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T12:58:58.454-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T12:58:58.549-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.116 seconds
[2023-12-21T13:00:07.828-0300] {processor.py:161} INFO - Started process (PID=7179) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:00:07.830-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:00:07.832-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:00:07.831-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:00:07.841-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:00:07.839-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:00:07.842-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:00:07.980-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.158 seconds
[2023-12-21T13:01:20.528-0300] {processor.py:161} INFO - Started process (PID=7275) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:01:20.529-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:01:20.530-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:01:20.530-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:01:20.536-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:01:20.535-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:01:20.537-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:01:20.635-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.112 seconds
[2023-12-21T13:02:27.216-0300] {processor.py:161} INFO - Started process (PID=7356) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:02:27.217-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:02:27.218-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:02:27.218-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:02:27.223-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:02:27.222-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:02:27.223-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:02:27.332-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.121 seconds
[2023-12-21T13:03:28.114-0300] {processor.py:161} INFO - Started process (PID=7421) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:03:28.115-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:03:28.116-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:03:28.116-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:03:28.122-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:03:28.121-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:03:28.123-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:03:28.230-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.122 seconds
[2023-12-21T13:04:56.594-0300] {processor.py:161} INFO - Started process (PID=7505) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:04:56.600-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:04:56.602-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:04:56.601-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:04:56.611-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:04:56.609-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:04:56.612-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:04:56.727-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.139 seconds
[2023-12-21T13:06:10.937-0300] {processor.py:161} INFO - Started process (PID=7577) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:06:10.962-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:06:10.964-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:06:10.963-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:06:10.971-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:06:10.969-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:06:10.971-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:06:11.065-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.136 seconds
[2023-12-21T13:07:25.934-0300] {processor.py:161} INFO - Started process (PID=7735) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:07:25.942-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:07:25.944-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:07:25.943-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:07:25.951-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:07:25.949-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:07:25.952-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:07:26.045-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.117 seconds
[2023-12-21T13:08:36.055-0300] {processor.py:161} INFO - Started process (PID=9015) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:08:36.072-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:08:36.074-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:08:36.074-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:08:36.082-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:08:36.080-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:08:36.082-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:08:36.181-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.132 seconds
[2023-12-21T13:09:39.796-0300] {processor.py:161} INFO - Started process (PID=9259) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:09:39.812-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:09:39.813-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:09:39.812-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:09:39.818-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:09:39.817-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:09:39.818-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:09:40.027-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.236 seconds
[2023-12-21T13:10:49.618-0300] {processor.py:161} INFO - Started process (PID=9596) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:10:49.634-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:10:49.636-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:10:49.635-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:10:49.645-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:10:49.643-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:10:49.646-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:10:49.759-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.148 seconds
[2023-12-21T13:11:55.431-0300] {processor.py:161} INFO - Started process (PID=10041) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:11:55.456-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:11:55.458-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:11:55.457-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:11:55.467-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:11:55.465-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:11:55.468-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:11:55.584-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.160 seconds
[2023-12-21T13:12:57.234-0300] {processor.py:161} INFO - Started process (PID=10118) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:12:57.236-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:12:57.238-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:12:57.237-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:12:57.247-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:12:57.245-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:12:57.248-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:12:57.373-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.147 seconds
[2023-12-21T13:13:59.044-0300] {processor.py:161} INFO - Started process (PID=10313) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:13:59.046-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:13:59.048-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:13:59.047-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:13:59.057-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:13:59.055-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:13:59.058-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:13:59.163-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.126 seconds
[2023-12-21T13:15:04.414-0300] {processor.py:161} INFO - Started process (PID=10473) to work on /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:15:04.430-0300] {processor.py:830} INFO - Processing file /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py for tasks to queue
[2023-12-21T13:15:04.432-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:15:04.431-0300] {dagbag.py:538} INFO - Filling up the DagBag from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:15:04.441-0300] {logging_mixin.py:188} INFO - [2023-12-21T13:15:04.439-0300] {dagbag.py:348} ERROR - Failed to import: /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
Traceback (most recent call last):
  File "/home/myc-ti-2/airflow_workspace/airflow_env/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py", line 5, in <module>
    import awswrangler as wr
ModuleNotFoundError: No module named 'awswrangler'
[2023-12-21T13:15:04.442-0300] {processor.py:842} WARNING - No viable dags retrieved from /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py
[2023-12-21T13:15:04.551-0300] {processor.py:183} INFO - Processing /home/myc-ti-2/airflow/dags/dags_utils/dags_utils.py took 0.145 seconds
